config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  as :user do
  	get "signin" => 'devise/sessions#new'
  	delete "signout" => 'devise/sessions#destroy'
  	get "signup" => 'devise/registrations#new'
  end
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'contactus' => 'pages#contactus'
  #get 'contact-us' => 'pages#contact-us'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>One Month Rails Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation Bar -->
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <div class="container">
        <%= link_to "The Money Checklist", root_path, class: "navbar-brand" %>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Contact", "#", class: "nav-link" %></li>
        </ul>
        <% if user_signed_in?%>
        <ul class="navbar-nav">
          <li class="nav-item float-right"><%= link_to "Log out", signout_path, method: :delete, class: "nav-link" %></li>
        </ul>
        <% else %>
        <ul class="navbar-nav">
          <li class="nav-item float-right"><%= link_to "Sign Up", signup_path, class: "nav-link btn btn-primary" %></li>
          <li class="nav-item float-right"><%= link_to "Sign In", signin_path, class: "nav-link" %></li>
        </ul>
        <% end %>
      </div>
    </nav>

    <!-- Flash Messages -->
    <% flash.each do |name,message| %>
      <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
    <% end %>

    <!-- Page Content -->
    <%= yield %>
    
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© 2016 The Money Checklist</p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>About us</h1>
        <p>This is the sample project I built for <a href="https://onemonthrails.com">One Month Rails</a>.</p>
    </div>
</div>

app/views/pages/contactus.html.erb
<h1>Contact Us</h1>
I'm a friendly guy, so don't hesitate to <a href="mailto:mattysallin@gmail.com?subject=Hiya">email me</a> if you have any questions.

app/views/pages/home.html.erb
<% if user_signed_in? %>
            <div class="jumbotron jumbotron-home">
                <div class="container">
                        <h1>Welcome back!</h1>
                </div>
        <% else %>
    <div class="jumbotron jumbotron-home">
        <div class="container">
            <center>   
                <h1>The Money Checklist</h1>
                <h3>Wanna get your financial act together but not sure where to start?</h3>
                <%= link_to "Start here »", "#", class: "btn btn-primary btn-lg" %>
            </center> 
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <center><h2>Debt</h2>
                <p>In debt? We all are. We'll tell you which to pay off and in what order. </p>
                <p><%= link_to "Pay off my debt", "#", class: "btn btn-secondary" %></p>
            </center>
            </div>
            <div class="col-md-4">
            <center>    
                <h2>Savings</h2>
                <p>Feel like you don't have enough saved up? Don't have ANY saved up? We'll show you how to get started and how much you really need. </p>
                <p><%= link_to "Build savings", "#", class: "btn btn-secondary" %></p>
            </center>
            </div>
            <div class="col-md-4">
            <center>
                <h2>Investment</h2>
                <p>IRAs, 401(k)s, ETFs...could investing be any more confusing? We'll guide you through it all. </p>
                <p><%= link_to "Grow a nest egg", "#", class: "btn btn-secondary" %></p>
            </center>
            </div>
        </div>
    </div>
<% end %> 